name: CI/CD Pipeline for Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build the React app
        run: npm run build
        env:
          REACT_APP_REPOS_PATH: ${{ secrets.REACT_APP_REPOS_PATH }}
          REACT_APP_GITHUB_TOKEN: ${{ secrets.REACT_APP_GITHUB_TOKEN }}

      - name: Set up s3cmd
        run: |
          sudo apt-get update
          sudo apt-get install -y s3cmd

      - name: Configure s3cmd
        run: |
          echo "[default]" > ~/.s3cfg
          echo "host_base = hcm.s3storage.vn" >> ~/.s3cfg
          echo "host_bucket = y" >> ~/.s3cfg
          echo "bucket_location = vn-south-1" >> ~/.s3cfg
          echo "signature_v2 = False" >> ~/.s3cfg
          echo "access_key = ${{ secrets.S3_ACCESS_KEY_ID }}" >> ~/.s3cfg
          echo "secret_key = ${{ secrets.S3_SECRET_ACCESS_KEY }}" >> ~/.s3cfg

      - name: Sync build files to S3-compatible bucket
        env:
          BUCKET_NAME: co-commit-viewer
          HOME: /home/runner # Ensure s3cmd looks here for .s3cfg
        run: |
          s3cmd sync --acl-public --delete-removed --no-mime-magic --guess-mime-type build/ s3://$BUCKET_NAME/
